lint:
  tags:
    - grid5000-docker
  image: debian:bullseye
  script:
    - apt-get update && apt-get -y --no-install-recommends install rubygems ruby-dev libffi-dev build-essential
    - gem install bundler
    - bundle install --gemfile=ci/Gemfile
    # Puppet manifests syntax check (equivalent to puppet parser validate) - The most important check
    - BUNDLE_GEMFILE=ci/Gemfile bundle exec rake --rakefile ci/rakefile_syntax syntax:manifests
    - BUNDLE_GEMFILE=ci/Gemfile bundle exec rake --rakefile ci/rakefile_syntax syntax:templates
    - BUNDLE_GEMFILE=ci/Gemfile bundle exec rake --rakefile ci/rakefile_syntax syntax:hiera
    # Puppet style check
    - BUNDLE_GEMFILE=ci/Gemfile bundle exec rake --rakefile ci/rakefile_lint lint

dryrun_all:
  tags:
   - grid5000-docker
  image: ${CI_REGISTRY}/grid5000/docker/kameleon:2.10.11.1-bullseye
  script:
   - for G5K_ENV in *.yaml kadeploy3-deploy-kernel/*.yaml from_grid5000_environment/*.yaml; do echo "** kameleon dryrun $G5K_ENV **"; kameleon build -d "$G5K_ENV"; done
  except:
   - tags

.defaults-build: &defaults-build
  tags:
   - grid5000-shell
  script:
   - /srv/ci-runner-scripts/bin/test-environment-recipes ${CI_JOB_NAME#build_}
  except:
   - tags
#  artifacts:
#   paths:
#    - build/*dsc
#    - build/*tar.gz
#   expire_in: '1 week'

.jenkins-scripts-env-wrapper: &jenkins-scripts-env-wrapper
  tags:
   - grid5000-shell
  script:
   - /srv/jenkins-scripts/bin/env-ci ${CI_JOB_NAME}
  except:
   - tags
  after_script:
   - /srv/jenkins-scripts/bin/env-ci cleanup ${CI_JOB_NAME}

build_debian12-x64-min:
  <<: *jenkins-scripts-env-wrapper

test_debian12-x64-min_nancy-grappe:
  <<: *jenkins-scripts-env-wrapper
  needs: ["build_debian12-x64-min"]

test_debian12-x64-min_rennes-paradoxe:
  <<: *jenkins-scripts-env-wrapper
  needs: ["build_debian12-x64-min"]

push_debian12-x64-min:
  <<: *jenkins-scripts-env-wrapper
  needs: ["build_debian12-x64-min"]
  parallel:
    matrix:
      - SITE: ['grenoble', 'lille', 'luxembourg', 'lyon', 'nancy', 'nantes', 'rennes', 'sophia', 'toulouse']
  when: manual
