stages:
 - dryrun
 - build

.defaults-dryrun: &defaults-dryrun
  stage: dryrun
  tags:
   - grid5000-docker
  image: debian:buster
  script:
   - apt-get update && apt-get -y install ruby ruby-dev ruby-ffi graphviz-dev build-essential && gem install kameleon-builder
   - kameleon dryrun $(echo $CI_JOB_NAME | cut -d _ -f 2).yaml
  except:
   - tags

.defaults-build: &defaults-build
  stage: build
  tags:
   - grid5000-shell
  script:
   - /srv/ci-runner-scripts/bin/test-environment-recipes $(echo $CI_JOB_NAME | cut -d _ -f 2)
  except:
   - tags
#  artifacts:
#   paths:
#    - build/*dsc
#    - build/*tar.gz
#   expire_in: '1 week'

### Dryrun
## x64
# Debian9
dryrun_debian9-x64-min:
  <<: *defaults-dryrun

# Debian10
dryrun_debian10-x64-min:
  <<: *defaults-dryrun

dryrun_debian10-x64-base:
  <<: *defaults-dryrun

dryrun_debian10-x64-nfs:
  <<: *defaults-dryrun

dryrun_debian10-x64-xen:
  <<: *defaults-dryrun

dryrun_debian10-x64-big:
  <<: *defaults-dryrun

dryrun_debian10-x64-std:
  <<: *defaults-dryrun

# Debian11
dryrun_debian11-x64-min:
  <<: *defaults-dryrun

dryrun_debian11-x64-base:
  <<: *defaults-dryrun

dryrun_debian11-x64-nfs:
  <<: *defaults-dryrun

dryrun_debian11-x64-xen:
  <<: *defaults-dryrun

dryrun_debian11-x64-big:
  <<: *defaults-dryrun

dryrun_debian11-x64-std:
  <<: *defaults-dryrun

# Debian testing
dryrun_debiantesting-x64-min:
  <<: *defaults-dryrun

# Ubuntu
dryrun_ubuntu1804-x64-min:
  <<: *defaults-dryrun

dryrun_ubuntu2004-x64-min:
  <<: *defaults-dryrun

# Centos
dryrun_centos7-x64-min:
  <<: *defaults-dryrun

dryrun_centos8-x64-min:
  <<: *defaults-dryrun

## arm64
# Debian10
dryrun_debian10-arm64-min:
  <<: *defaults-dryrun

dryrun_debian10-arm64-base:
  <<: *defaults-dryrun

dryrun_debian10-arm64-nfs:
  <<: *defaults-dryrun

dryrun_debian10-arm64-xen:
  <<: *defaults-dryrun

dryrun_debian10-arm64-big:
  <<: *defaults-dryrun

dryrun_debian10-arm64-std:
  <<: *defaults-dryrun

# Debian11
dryrun_debian11-arm64-min:
  <<: *defaults-dryrun

dryrun_debian11-arm64-base:
  <<: *defaults-dryrun

dryrun_debian11-arm64-nfs:
  <<: *defaults-dryrun

dryrun_debian11-arm64-xen:
  <<: *defaults-dryrun

dryrun_debian11-arm64-big:
  <<: *defaults-dryrun

dryrun_debian11-arm64-std:
  <<: *defaults-dryrun

# Debian testing
dryrun_debiantesting-arm64-min:
  <<: *defaults-dryrun

# Ubuntu
dryrun_ubuntu1804-arm64-min:
  <<: *defaults-dryrun

## ppc64
# Debian11
dryrun_debian11-ppc64-min:
  <<: *defaults-dryrun

# Debian testing
dryrun_debiantesting-ppc64-min:
  <<: *defaults-dryrun

### Build
## x64
# Debian 9
build_debian9-x64-min:
  <<: *defaults-build

# Debian 10
build_debian10-x64-std:
  <<: *defaults-build

# Debian 11
  <<: *defaults-build
build_debian11-x64-std:
  <<: *defaults-build

# Debian testing
build_debiantesting-x64-min:
  <<: *defaults-build

# Ubuntu
build_ubuntu1804-x64-min:
  <<: *defaults-build

build_ubuntu2004-x64-min:
  <<: *defaults-build

# Centos
build_centos7-x64-min:
  <<: *defaults-build

build_centos8-x64-min:
  <<: *defaults-build
