stages:
 - dryrun
 - build

.defaults: &defaults
  tags:
   - grid5000-shell
  artifacts:
     paths:
      - apt-history.log
     expire_in: '1 week'

.defaults-dryrun: &defaults-dryrun
  stage: dryrun
  tags:
   - grid5000-docker
  script:
   - /usr/bin/env tools/setup_grid5000.sh
   - kameleon info --dryrun virtualbox/$(echo $CI_JOB_NAME | cut -d _ -f 2).yaml

.defaults-build: &defaults-build
  stage: build
  tags:
   - grid5000-shell
  script:
   - /srv/ci-runner-scripts/bin/test-environment-recipes virtualbox/$(echo $CI_JOB_NAME | cut -d _ -f 2)

dryrun_jessie-x64-min:
  <<: *defaults-dryrun

dryrun_jessie-x64-base:
  <<: *defaults-dryrun

dryrun_jessie-x64-nfs:
  <<: *defaults-dryrun

dryrun_jessie-x64-xen:
  <<: *defaults-dryrun

dryrun_jessie-x64-big:
  <<: *defaults-dryrun

dryrun_jessie-x64-std:
  <<: *defaults-dryrun


build_jessie-x64-std:
  <<: *defaults-build
