stages:
 - dryrun
 - setup
 - debian
 - centos
 - centosstream
 - rocky
 - ubuntu

clone-refrepo:
  stage: setup
  image: bitnami/git:latest
  tags:
    - linux
  when: manual
  variables:
    # NOTE: in order to change this, when the pipeline is created, click on the
    # job name (not the play button), and use the UI to change the variable's
    # value.
    REFREPO_BRANCH: master
    GENERATE_OS:
    TEST_CLUSTERS:
  script:
    - echo ${REFREPO_BRANCH}
    - git clone https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.inria.fr/grid5000/reference-repository.git --depth 1 -b ${REFREPO_BRANCH}
    - rm -rf generated && mkdir generated
    - echo "$GENERATE_OS" > generated/generate_os
    - echo "$TEST_CLUSTERS" > generated/test_clusters
  artifacts:
    paths:
      - reference-repository
      - generated


# NOTE: this is a standalone job because gitlab requires <5MB artifacts for
# dynamic child pipelines.
generate-config:
  stage: setup
  image: ruby:3.3
  tags:
    - linux
  needs:
    - clone-refrepo
  variables:
    RUBYLIB: reference-repository/lib
  script:
    - GENERATE_OS=$(cat generated/generate_os) TEST_CLUSTERS=$(cat generated/test_clusters) ruby ci/gitlab/gen_jobs.rb -o generated
  artifacts:
    paths:
      - generated

include:
  # FIXME: restore this part of the config when everything is ready!
  #- 'ci/gitlab/sanity.yml'
  # FIXME: the part below could actually be generated too; but it means one
  # single downstream pipeline first, then one per child
  - 'ci/gitlab/matrix-archs.yml'
  - local: 'ci/gitlab/gen-job-os.yml'
    inputs:
      os: debian
      version: "10"
      extends: .matrix-all-archs
  - local: 'ci/gitlab/gen-job-os.yml'
    inputs:
      os: debian
      version: "11"
      extends: .matrix-all-archs
  - local: 'ci/gitlab/gen-job-os.yml'
    inputs:
      os: debian
      version: "12"
      extends: .matrix-all-archs
  - local: 'ci/gitlab/gen-job-os.yml'
    inputs:
      os: debian
      version: testing
      extends: .matrix-all-archs
  - local: 'ci/gitlab/gen-job-os.yml'
    inputs:
      os: debian
      version: l4t1135
      extends: .matrix-arm
  - local: 'ci/gitlab/gen-job-os.yml'
    inputs:
      os: centosstream
      version: "8"
      extends: .matrix-x-arm
  - local: 'ci/gitlab/gen-job-os.yml'
    inputs:
      os: centosstream
      version: "9"
      extends: .matrix-x-arm
  - local: 'ci/gitlab/gen-job-os.yml'
    inputs:
      os: centos
      version: "7"
      extends: .matrix-all-archs
  - local: 'ci/gitlab/gen-job-os.yml'
    inputs:
      os: centos
      version: "8"
      extends: .matrix-all-archs
  - local: 'ci/gitlab/gen-job-os.yml'
    inputs:
      os: ubuntu
      version: "2004"
      extends: .matrix-all-archs
  - local: 'ci/gitlab/gen-job-os.yml'
    inputs:
      os: ubuntu
      version: "2204"
      extends: .matrix-x-arm
  - local: 'ci/gitlab/gen-job-os.yml'
    inputs:
      os: ubuntu
      version: "l4t200435"
      extends: .matrix-arm
  - local: 'ci/gitlab/gen-job-os.yml'
    inputs:
      os: rocky
      version: "8"
      extends: .matrix-x-arm
  - local: 'ci/gitlab/gen-job-os.yml'
    inputs:
      os: rocky
      version: "9"
      extends: .matrix-x-arm
  - local: 'ci/gitlab/gen-job-os.yml'
    inputs:
      os: rocky
      version: "9"
      extends: .matrix-x-arm
