stages:
 - dryrun
 - build

.defaults-dryrun: &defaults-dryrun
  stage: dryrun
  tags:
   - grid5000-docker
  image: debian:buster
  script:
   - apt-get update && apt-get -y install ruby ruby-dev ruby-ffi graphviz-dev build-essential && gem install kameleon-builder
   - kameleon dryrun $(echo $CI_JOB_NAME | cut -d _ -f 2).yaml
  except:
   - tags

.defaults-build: &defaults-build
  stage: build
  tags:
   - grid5000-shell
  script:
   - /srv/ci-runner-scripts/bin/test-environment-recipes $(echo $CI_JOB_NAME | cut -d _ -f 2)
  except:
   - tags
#  artifacts:
#   paths:
#    - build/*dsc
#    - build/*tar.gz
#   expire_in: '1 week'


dryrun_centos8-x64-min:
  <<: *defaults-dryrun

dryrun_centos7-x64-min:
  <<: *defaults-dryrun

dryrun_ubuntu1804-x64-min:
  <<: *defaults-dryrun

dryrun_debiantesting-x64-min:
  <<: *defaults-dryrun

dryrun_debian9-x64-min:
  <<: *defaults-dryrun

dryrun_debian10-x64-min:
  <<: *defaults-dryrun

dryrun_debian10-x64-base:
  <<: *defaults-dryrun

dryrun_debian10-x64-nfs:
  <<: *defaults-dryrun

dryrun_debian10-x64-xen:
  <<: *defaults-dryrun

dryrun_debian10-x64-big:
  <<: *defaults-dryrun

dryrun_debian10-x64-std:
  <<: *defaults-dryrun

dryrun_debian10-arm64-min:
  <<: *defaults-dryrun

dryrun_debian10-arm64-base:
  <<: *defaults-dryrun

dryrun_debian10-arm64-nfs:
  <<: *defaults-dryrun

dryrun_debian10-arm64-xen:
  <<: *defaults-dryrun

dryrun_debian10-arm64-big:
  <<: *defaults-dryrun

dryrun_debian10-arm64-std:
  <<: *defaults-dryrun


build_centos8-x64-min:
  <<: *defaults-build

build_centos7-x64-min:
  <<: *defaults-build

build_ubuntu1804-x64-min:
  <<: *defaults-build

build_debiantesting-x64-min:
  <<: *defaults-build

build_debian9-x64-min:
  <<: *defaults-build

build_debian10-x64-std:
  <<: *defaults-build
