.defaults: &defaults
  tags:
   - grid5000-shell
  artifacts:
     paths:
      - apt-history.log
     expire_in: '1 week'

jessie-x64-min:
  <<: *defaults
  script: /srv/ci-runner-scripts/bin/test-environment-jessie jessie-x64-min min

jessie-x64-base:
  <<: *defaults
  script: /srv/ci-runner-scripts/bin/test-environment-jessie jessie-x64-base base

jessie-x64-nfs:
  <<: *defaults
  script: /srv/ci-runner-scripts/bin/test-environment-jessie jessie-x64-nfs nfs

jessie-x64-xen:
  <<: *defaults
  script: /srv/ci-runner-scripts/bin/test-environment-jessie jessie-x64-xen xen

jessie-x64-big:
  <<: *defaults
  script: /srv/ci-runner-scripts/bin/test-environment-jessie jessie-x64-big big

jessie-x64-std:
  <<: *defaults
  script: /srv/ci-runner-scripts/bin/test-environment-jessie jessie-x64-std std
