stages:
 - dryrun
 - build

lint:
  stage: .pre
  tags:
    - grid5000-docker
  image: debian:bullseye
  script:
    - apt-get update && apt-get -y --no-install-recommends install rubygems ruby-dev libffi-dev build-essential
    - gem install bundler
    - bundle install --gemfile=ci/Gemfile
    # Puppet manifests syntax check (equivalent to puppet parser validate) - The most important check
    - BUNDLE_GEMFILE=ci/Gemfile bundle exec rake --rakefile ci/rakefile_syntax syntax:manifests
    - BUNDLE_GEMFILE=ci/Gemfile bundle exec rake --rakefile ci/rakefile_syntax syntax:templates
    - BUNDLE_GEMFILE=ci/Gemfile bundle exec rake --rakefile ci/rakefile_syntax syntax:hiera
    # Puppet style check
    - BUNDLE_GEMFILE=ci/Gemfile bundle exec rake --rakefile ci/rakefile_lint lint

dryrun_all:
  stage: dryrun
  tags:
   - grid5000-docker
  image: ${CI_REGISTRY}/grid5000/docker/kameleon:2.10.8.1-bullseye
  script:
   - for G5K_ENV in *.yaml kadeploy3-deploy-kernel/*.yaml from_grid5000_environment/*.yaml; do echo "** kameleon dryrun $G5K_ENV **"; kameleon dryrun "$G5K_ENV"; done
  except:
   - tags

.defaults-build: &defaults-build
  stage: build
  tags:
   - grid5000-shell
  script:
   - /srv/ci-runner-scripts/bin/test-environment-recipes ${CI_JOB_NAME#build_}
  except:
   - tags
#  artifacts:
#   paths:
#    - build/*dsc
#    - build/*tar.gz
#   expire_in: '1 week'

### Build
## x64
# Debian 10
build_debian10-x64-std:
  <<: *defaults-build

# Debian 11
  <<: *defaults-build
build_debian11-x64-std:
  <<: *defaults-build

# Debian testing
build_debiantesting-x64-min:
  <<: *defaults-build

# Ubuntu
build_ubuntu2004-x64-min:
  <<: *defaults-build

build_ubuntu2204-x64-nfs:
  <<: *defaults-build

# Centos
build_centos7-x64-min:
  <<: *defaults-build

build_centos8-x64-min:
  <<: *defaults-build

# Centos Stream
build_centosstream8-x64-min:
  <<: *defaults-build

build_centosstream9-x64-min:
  <<: *defaults-build

# Rocky
build_rocky8-x64-min:
  <<: *defaults-build

build_rocky9-x64-min:
  <<: *defaults-build

# MiniOS Bullseye
build_kadeploy3-deploy-kernel/kadeploy3-deploy-kernel-bullseye:
  <<: *defaults-build

# from_grid5000_environment
build_from_grid5000_environment/base:
  <<: *defaults-build

