#==============================================================================
# vim: softtabstop=2 shiftwidth=2 expandtab fenc=utf-8 cc=81 tw=80
#==============================================================================
#
# DESCRIPTION: arm64 base recipe
#
#==============================================================================
---
extend: ../base.yaml
# Global variables use by Kameleon engine and the steps
global:
  arch: aarch64
  installer_iso_arch: aarch64
  qemu_arch: aarch64
  qemu_enable_kvm: true
  qemu_uefi: true

bootstrap:
  - "@base"

setup:
  - "@base"

export:
  - "@base"
