# This contains the minimal configuration for a NixOS image with a few additions for:
# - Compatibility with all clusters (kernel modules and drivers)
# - Compatibility with the postinstall customizations (Network, kernel params and filesystems, ssh access)
# - Compatibility with our network stack (DHCP, IPv6)
#
# Some non obvious standard alternatives are provided with a "Standard:" comment
{
  pkgs,
  lib,
  ...
}: let
  version = "$GENERATED_ENV_VERSION";
  commitSha = "$CI_COMMIT_SHA";
  arch = if pkgs.stdenv.hostPlatform.isAarch64 then "arm64" else "x64";
in {

  # The min variant only includes necessary packages
  environment.systemPackages = with pkgs; [
    inetutils # Network utilities, necessary to simplify automated testing with jenkins (to have ping6 available)
    vim
    rsync
    gnupg
  ];

  system.stateVersion = "26.05";

  # Ensure compatibility with all clusters
  # Standard: hardware is defined via a specific hardware-configuration.nix per machine
  hardware.enableAllHardware = true;
  # For compatibility with RAID controller like on larochette and pyxis
  boot.initrd.availableKernelModules = ["mpi3mr" "mpt3sas"];

  services.openssh = {
    enable = true;
  };

  # Fix possible timeout on boot waiting for a TPM device
  boot.initrd.systemd.tpm2.enable = false;
  systemd.tpm2.enable = false;

  time.timeZone = "Europe/Paris";
  boot.loader = {
    # Grub is required for kadeploy compatiblity and PXE boot
    grub = {
      enable = true;
      device = "nodev";
    };
    efi = {
      efiSysMountPoint = "/boot/efi";
    };
  };

  # The postinstall will overwrite the "/" to the correct partition depending on the kadeploy arguments. Here this is set to fallback to the default PROD partition
  # To simplify the postinstall, we are parsing the fstab generated by the postinstall to generate the correct fileSystems configuration
  # Standard: the filesystem is generally described in hardware-configuration.nix using `filesystems = [ ... ];`
  imports = [ ./fstab-parser.nix ];
  fileSystems = {
    "/" = lib.mkDefault {
      device = "/dev/disk/by-partlabel/KDPL_DEPLOY_disk0";
      fsType = "ext4";
    };
    "/boot/efi" = lib.mkDefault {
      device = "/dev/disk/by-partlabel/efi";
      fsType = "vfat";
      options = ["fmask=0022" "dmask=0022"];
    };
  };

  # On initial deployment, kadeploy will write the kernel parameters to kadeploy-cmdline.txt
  # Standard: boot.kernelParams is a static list of strings
  boot.kernelParams = let
    cmdlineFile = ./kadeploy-cmdline.txt;
    rawParams = if builtins.pathExists cmdlineFile
                then builtins.readFile cmdlineFile
                else "";
    paramsList = lib.splitString " " (lib.trim rawParams);
    # Ignore empty parameters and the initial init= parameter
    isWantedParam = x: x != "" && !(lib.hasPrefix "init=" x);
  in
    builtins.filter isWantedParam paramsList;

  # We are using NetworkManager here since we already have a way to customize the connections through the g5k-postinstall
  # Standard: The default uses dhcpcd which works well with Grid'5000 DHCPv6 and FQDN resolution
  # However, using Networkmanager requires a few fixes (see below) regarding DHCPv6 and the FQDN resolution
  # * IPv6: NetworkManager defaults to SLAAC ("auto") and idly waits for Router Advertisements unlike dhcpcd
  # * FQDN: NetworkManager strips the domain name and sets the kernel hostname strictly to the short name
  networking.networkmanager = {
    enable = true;

    connectionConfig = {
      "ipv6.method" = "dhcp"; # Request DHCPv6 even without SLAAC Router Advertisements
      "ipv6.dhcp-duid" = "llt"; # Standard DUID format (Link-layer + time) for Grid'5000 DHCPv6
    };
  };
  # Prioritize DNS resolution so `hostname -f` asks DNS for the canonical FQDN
  system.nssDatabases.hosts = lib.mkForce [
    "mymachines"
    "files"
    "dns"
    "myhostname"
  ];
  # Set the hostname with DHCP
  networking.hostName = "";

  # Informative files checked by our automated tests
  environment.etc = {
    "grid5000/release".text = ''
      nixos2605-${arch}-min-${version}
      ${commitSha}
    '';
    "motd".text = ''
      nixos2605-${arch}-min-${version}
      (Image based on NixOS 26.05 for ${arch})
      Maintained by support-staff <support-staff@lists.grid5000.fr>
    '';
  };
  # Standard: The motd can directly be specfied with `users.motd = "..."`
  users.motdFile = "/etc/motd";

  # Automatically merges all rules from ./udev_rules into the system udev rules
  # Standard: It may be simpler to use services.udev.extraRules for a few additions
  services.udev.packages = if builtins.pathExists ./udev_rules then [
    (pkgs.linkFarm "extra-udev-rules" [
      { name = "etc/udev/rules.d"; path = ./udev_rules; }
    ])
  ] else [];
}
