{ lib, ... }:

let
  # Read the plain-text fstab generated by the postinstall
  fstabText =
    if builtins.hasAttr "fstab" (builtins.readDir ./.)
    then builtins.readFile ./fstab
    else "";

  # Split the file into a list of lines
  lines = lib.splitString "\n" fstabText;

  # Filter out comments and empty lines
  isMountLine = line: builtins.match "^[ \t]*[^# \t].*" line != null;
  validLines = builtins.filter isMountLine lines;

  # Helper to translate fstab UUID=/LABEL= syntax into NixOS absolute paths
  resolveDevice = dev:
    if lib.hasPrefix "UUID=" dev then
      "/dev/disk/by-uuid/" + lib.removePrefix "UUID=" dev
    else if lib.hasPrefix "LABEL=" dev then
      "/dev/disk/by-label/" + lib.removePrefix "LABEL=" dev
    else if lib.hasPrefix "PARTUUID=" dev then
      "/dev/disk/by-partuuid/" + lib.removePrefix "PARTUUID=" dev
    else if lib.hasPrefix "PARTLABEL=" dev then
      "/dev/disk/by-partlabel/" + lib.removePrefix "PARTLABEL=" dev
    else
      dev; # Return as-is (e.g., /dev/sda1 or nfs:/export)

  # Parse each valid fstab line into an attribute set
  parseLine = line:
    let
      m = builtins.match "^[ \t]*([^ \t]+)[ \t]+([^ \t]+)[ \t]+([^ \t]+)[ \t]+([^ \t]+).*$" line;
    in {
      # Use our helper to ensure the device is an absolute path
      device = resolveDevice (builtins.elemAt m 0);
      mountPoint = builtins.elemAt m 1;
      fsType = builtins.elemAt m 2;
      options = lib.splitString "," (builtins.elemAt m 3);
    };

  parsed = map parseLine validLines;

  # Separate swap partitions from standard filesystems
  isSwap = p: p.fsType == "swap";
  swaps = builtins.filter isSwap parsed;
  mounts = builtins.filter (p: !isSwap p) parsed;

in {
  # Configure Swap
  swapDevices = map (s: { device = s.device; }) swaps;

  # Configure Filesystems
  fileSystems = builtins.listToAttrs (map (m: {
    name = m.mountPoint;
    value = {
      device = m.device;
      fsType = m.fsType;
      options = m.options;
    };
  }) mounts);
}
