import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

import type { Metadata, Viewport } from "next";

import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import CssBaseline from '@mui/material/CssBaseline';
import OpenIDProvider from '@/components/OpenIDProvider';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/*
          NOTE: passing "prepend: true" here is important. It allows us to override
          Material UI styles in components.
        */}
        <AppRouterCacheProvider options={{ prepend: true }}>
          <CssBaseline />
          <OpenIDProvider>
            {children}
          </OpenIDProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
