# Software Install
- deb_components: "main"
- deb_backports: true

- configure_source_list:
  - exec_in: echo "Not changing Ubuntu apt sources"

- update_repositories:
  # Deactivate the check to make the cache system works after a while...
  - exec_in: echo "No update needed"

- disable_automatic_apt_upgrades:
  - test:
    - exec_local: test "$${g5k_release_number}" -ge "2204"
    - group:
      - exec_in: systemctl disable apt-daily.timer apt-daily.service
      - exec_in: systemctl disable apt-daily-upgrade.timer apt-daily-upgrade.service
      - exec_in: systemctl disable unattended-upgrades.service
